brenta:
  password: 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
  theme_id: ""
  store: jimmyjane-technical-challenge-4.myshopify.com
lorenzol:
  password: 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
  theme_id: "114845843618"
  store: jimmyjane-technical-challenge-3.myshopify.com
matthewb:
  password: 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
  theme_id: "115199213719"
  store: jimmyjane-technical-challenge-2.myshopify.com
viviana:
  password: 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
  theme_id: "115464372386"
  store: jimmyjane-technical-challenge.myshopify.com
