development:
  password: ${CHALLENGE_JJ_API_PW}
  theme_id: "114890539170"
  store: ${CHALLENGE_JJ_STORE_DOMAIN}
production:
  password: ${CHALLENGE_JJ_API_PW}
  theme_id: "114484445346"
  store: ${CHALLENGE_JJ_STORE_DOMAIN}
